// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7MwatBNtpsnCBfOQla_NjtHl3ggqUT3I',
    appId: '1:387405403057:web:dc0ab88d9ffede1633a390',
    messagingSenderId: '387405403057',
    projectId: 'my-rights-d32cb',
    authDomain: 'my-rights-d32cb.firebaseapp.com',
    storageBucket: 'my-rights-d32cb.firebasestorage.app',
    measurementId: 'G-ENH5PDCXCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT9kP-4fjDC6webIXmR-imL8gjZjJJ2UY',
    appId: '1:387405403057:android:2c4bd447dc9f31ad33a390',
    messagingSenderId: '387405403057',
    projectId: 'my-rights-d32cb',
    storageBucket: 'my-rights-d32cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rfeaLiGbpyqxARRcnHQh9dKFCaVRABk',
    appId: '1:387405403057:ios:4cf03f4a59f1bd3133a390',
    messagingSenderId: '387405403057',
    projectId: 'my-rights-d32cb',
    storageBucket: 'my-rights-d32cb.firebasestorage.app',
    iosBundleId: 'com.example.myRightsMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rfeaLiGbpyqxARRcnHQh9dKFCaVRABk',
    appId: '1:387405403057:ios:4cf03f4a59f1bd3133a390',
    messagingSenderId: '387405403057',
    projectId: 'my-rights-d32cb',
    storageBucket: 'my-rights-d32cb.firebasestorage.app',
    iosBundleId: 'com.example.myRightsMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7MwatBNtpsnCBfOQla_NjtHl3ggqUT3I',
    appId: '1:387405403057:web:cf0434462693eae033a390',
    messagingSenderId: '387405403057',
    projectId: 'my-rights-d32cb',
    authDomain: 'my-rights-d32cb.firebaseapp.com',
    storageBucket: 'my-rights-d32cb.firebasestorage.app',
    measurementId: 'G-1SNS45633R',
  );
}
